### ISSUE TITLE
change EPUB Version implementation

### ISSUE THREAD

**Issue by aferditamuriqi** [readium/r2-shared-kotlin#37]
Used as an internal in Swift and Kotlin for parsing
Shouldn't be part of the core model
Might be better using a cascade instead for parsing

**Comment by HadrienGardeur** [comment]
Might be related to https://github.com/readium/architecture/issues/112

**Comment by qnga** [comment]
Publication.version is not used any more for parsing in Kotlin. It might be safely removed.

**Comment by mickael-menu** [comment]
> Publication.version is not used any more for parsing in Kotlin. It might be safely removed.

This info is still useful for the reading apps, but it should probably be in the `FileFormat`.
