### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by nurzhaussyn** [readium/r2-shared-kotlin#62]
<img width="1280" alt="Снимок экрана 2019-06-14 в 15 44 17" src="https://user-images.githubusercontent.com/16848122/59500460-4938d280-8ebb-11e9-99b0-72b4e6a79635.png">

I suppose that problem from shared lib. What is wrong ?

**Comment by aferditamuriqi** [comment]
This seems to be a problem with jitpack, we'll look into why the libraries weren't build

**Comment by aferditamuriqi** [comment]
@nurzhaussyn this should be fixed now, please try again, you might have to reload the gradle dependencies
