### ISSUE TITLE
MultilanguageString

### ISSUE THREAD

**Issue by qnga** [readium/r2-shared-kotlin#87]
I can't fully understand the intent behind MultilanguageString objects, used for example for titles. In the Readium manifest specification, a title is either a String, or a map from language to title, not both.
In the [Epub Metadata Parsing Guide](https://readium.org/architecture/streamer/parser/metadata.html) one can't find any mention of "singleString" either.
Since, content from <dc:title> is put into the map after determining the tag language, what is singleString for? Should it contain a copy of the title in the default language for metadata, computed as specified in the Epub Metadata Parsing Guide?

**Comment by mickael-menu** [comment]
Yes it's wrong, I will refactor this as a sealed class.

Here's the Swift version that should be correct: https://github.com/readium/r2-shared-swift/blob/develop/r2-shared-swift/Publication/Web%20Publication/LocalizedString.swift

**Comment by qnga** [comment]
Will we use the non-localized-case in native formats parsing? Only when no xml:lang is defined and publication has no default language? Or when there is only one variant? It looks like a shortcut for handwriting, and not designed for automatic parsing.

**Comment by mickael-menu** [comment]
Good question. [You can see here](https://github.com/readium/r2-streamer-swift/blob/630d8953cbad98fb229233caa9d98b2ce16474b3/r2-streamer-swift/Parser/EPUB/EPUBMetadataParser.swift#L453-L457) that in Swift I added [a fallback on xml:lang](https://github.com/readium/r2-streamer-swift/blob/630d8953cbad98fb229233caa9d98b2ce16474b3/r2-streamer-swift/Parser/EPUB/EPUBMetadataParser.swift#L70-L76) for the language of the default string, but only if there are several translations available.

The rationale was that this is redundant with `publication.metadata.languages` in the model. The goal of these localized strings is to provide translations when available, not to know the language of the string – unless it differs from the publication's language.

For other formats embedding a RWPM as a JSON manifest (LCPDF, audiobooks), we are parsing the JSON as-is, so the default language is definitely not added in all the strings.

(Btw we have a Slack at Readium, if you want to join: http://readium-slack.herokuapp.com/)

**Comment by qnga** [comment]
Your choice seems to be reasonable, but goes against the Epub Parsing Guide. If all people agree, it should be modified (and some other points clarified I think).

**Comment by mickael-menu** [comment]
Can you link to the part where you think this goes against the guide?

**Comment by qnga** [comment]
> While the default context is very flexible in the way each metadata can be represented, when parsing a publication in the streamer we always use the most complex form for each metadata to harmonize our output.

> To determine the default language for metadata, check:

    if the package has an xml:lang attribute;
    the primary language of the publication.

I'm not sure, but if I have to give an interpretation of this, I will say that the unlocalized version should not be used in Epub parsing.

**Comment by mickael-menu** [comment]
So we're actually going to change the model to remove the "nonlocalized" case.

It looks like that on Kotlin right now:

https://github.com/readium/r2-shared-kotlin/blob/dba8aad55b0126873c9b7ebe9aff69aa55dec939/r2-shared/src/main/java/org/readium/r2/shared/publication/webpub/LocalizedString.kt#L23-L28

Before finalizing this form, I'll have to check if this is a non-breaking change on Swift.

**Comment by qnga** [comment]
> package org.readium.r2.shared.publication.webpub

That's only for webpub publications, or Readium manifest and publications will use parts of the webpub model?

**Comment by mickael-menu** [comment]
It's for the [Readium Web Publication Manifest model](https://readium.org/webpub-manifest/), not for the W3C Web Publication.

In the parent package will reside the models used in R2: `Publication` (which will delegate to the `WebPublication` for metadata and augment it with features needed by the navigator), `Locator`, `UserSettings`, etc.

**Comment by mickael-menu** [comment]
Actually I moved everything under `publication`, and merged `Publication` and `WebPublication` together.
